"""DB access for patients. No HTTP, no business rules — see app/services/patient_service.py.

Commit/rollback is handled centrally by the `get_db` dependency / `webhook_session` (see
app/db/session.py); this module only flushes so autogenerated values (patient_id,
timestamps) and constraint violations are visible before the request finishes.
"""

from __future__ import annotations

import uuid
from datetime import UTC, date, datetime

from sqlalchemy import ColumnElement, func, select
from sqlalchemy.exc import DataError, IntegrityError
from sqlalchemy.ext.asyncio import AsyncSession

from app.core.errors import ConflictError, ValidationFailedError
from app.models.patient import Patient


class PatientRepository:
    """Async, DB-only access to the `patients` table."""

    def __init__(self, session: AsyncSession) -> None:
        self._session = session

    async def get_by_id(self, patient_id: uuid.UUID) -> Patient | None:
        stmt = select(Patient).where(Patient.patient_id == patient_id, Patient.deleted_at.is_(None))
        result = await self._session.execute(stmt)
        return result.scalar_one_or_none()

    async def list_patients(
        self,
        *,
        last_name: str | None = None,
        date_of_birth: date | None = None,
        phone_number: str | None = None,
        limit: int = 50,
        offset: int = 0,
    ) -> tuple[list[Patient], int]:
        """Newest first, excluding soft-deleted rows. Returns (page, total matching)."""
        conditions: list[ColumnElement[bool]] = [Patient.deleted_at.is_(None)]
        if last_name is not None:
            conditions.append(func.lower(Patient.last_name) == last_name.lower())
        if date_of_birth is not None:
            conditions.append(Patient.date_of_birth == date_of_birth)
        if phone_number is not None:
            conditions.append(Patient.phone_number == phone_number)

        total = (
            await self._session.execute(
                select(func.count()).select_from(Patient).where(*conditions)
            )
        ).scalar_one()

        stmt = (
            select(Patient)
            .where(*conditions)
            .order_by(Patient.created_at.desc())
            .limit(limit)
            .offset(offset)
        )
        result = await self._session.execute(stmt)
        return list(result.scalars().all()), total

    async def count_active(self, *, created_since: datetime | None = None) -> int:
        conditions: list[ColumnElement[bool]] = [Patient.deleted_at.is_(None)]
        if created_since is not None:
            conditions.append(Patient.created_at >= created_since)
        stmt = select(func.count()).select_from(Patient).where(*conditions)
        return (await self._session.execute(stmt)).scalar_one()

    async def find_active_by_phone(self, phone_number: str) -> list[Patient]:
        stmt = (
            select(Patient)
            .where(Patient.phone_number == phone_number, Patient.deleted_at.is_(None))
            .order_by(Patient.created_at.desc())
        )
        result = await self._session.execute(stmt)
        return list(result.scalars().all())

    async def get_by_source_call_id(self, source_call_id: str) -> Patient | None:
        """Includes soft-deleted rows: a retried tool call must still find its own record."""
        stmt = select(Patient).where(Patient.source_call_id == source_call_id)
        result = await self._session.execute(stmt)
        return result.scalar_one_or_none()

    async def create(self, fields: dict[str, object]) -> Patient:
        patient = Patient(**fields)
        try:
            async with self._session.begin_nested():
                self._session.add(patient)
                await self._session.flush()
        except (IntegrityError, DataError) as exc:
            raise _translate_integrity_error(exc) from exc
        await self._session.refresh(patient)
        return patient

    async def update(self, patient: Patient, fields: dict[str, object]) -> Patient:
        for key, value in fields.items():
            setattr(patient, key, value)
        await self._flush(patient)
        return patient

    async def soft_delete(self, patient: Patient) -> Patient:
        patient.deleted_at = datetime.now(UTC)
        await self._flush(patient)
        return patient

    async def _flush(self, patient: Patient) -> None:
        """Flush pending changes inside a savepoint, so a constraint violation rolls back
        only this write and the request's transaction stays usable."""
        try:
            async with self._session.begin_nested():
                await self._session.flush()
        except (IntegrityError, DataError) as exc:
            raise _translate_integrity_error(exc) from exc
        await self._session.refresh(patient)


def _translate_integrity_error(
    exc: IntegrityError | DataError,
) -> ConflictError | ValidationFailedError:
    """Map a raw DB constraint violation to a domain error; never leak the DB message."""
    detail = str(exc.orig).lower() if exc.orig else ""
    if "unique" in detail or "duplicate key" in detail:
        return ConflictError("A conflicting record already exists.")
    return ValidationFailedError("The provided data violates a database constraint.")
